Maquettage page calendrier
shiipou/simplon-2024-brief-06-TooManyChoco pull request #52
Opened 2024-05-14 12:26 UTC by tcht-marie

## About this PR

## Technical highlight/advice

## How to test my changes

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 other
- [ ] 🙅 no documentation needed

2024-05-14 12:31 UTC, jebourdeau approved these changes

2024-05-14 12:33 UTC, morganb75 approved these changes

2024-05-14 12:38 UTC, CharlotteCharrier approved these changes

2024-05-14 12:38 UTC, SFaucher26 approved these changes

2024-05-14 12:38 UTC, corantoine approved these changes

2024-05-14 13:13 UTC, JCMaif approved these changes

2024-05-15 07:31 UTC, shiipou requested changes
Invalid PR name, can you change it to use ConvCo ? (Conventionnal commit names)

2024-05-15 07:31 UTC, shiipou requested changes

2024-05-15 07:31 UTC, shiipou commented on app/src/main/java/io/simplon/toomanychoco/db/DbConnector.java
> +	private static final String JDBC_URL = "jdbc:postgresql://localhost:5432/toomanychoco";
Do not change the database credentials for other peoples.
```suggestion
	private static final String JDBC_URL = "jdbc:postgresql://localhost:5432/TooManyChoco";
```

2024-05-15 07:51 UTC, shiipou approved these changes

2024-05-15 07:53 UTC, merged