6 implmentation du front du dtails dun event
shiipou/simplon-2024-brief-06-TooManyChoco pull request #54
Opened 2024-05-15 12:11 UTC by Omar1H1

## About this PR

## Technical highlight/advice

## How to test my changes

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes
- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 other
- [ ] 🙅 no documentation needed

2024-05-15 15:06 UTC, Jean-Charles-Audebert approved these changes
A compléter : En cas de plusieurs viennoiseries choisies, comment s'affichent les résultats?

2024-05-16 08:54 UTC, Omar1H1 commented on react-app/src/index.css
> +}
No, you're right, i just removed it, thanks for the feedback :) .

2024-05-16 08:55 UTC, jebourdeau approved these changes

2024-05-16 09:33 UTC, shiipou approved these changes

2024-05-16 09:33 UTC, shiipou requested changes
Can you add some documentation about your changes

2024-05-16 09:44 UTC, tcht-marie approved these changes

2024-05-16 11:07 UTC, jbouhet79 commented
Comment tester votre projet ?

2024-05-16 11:25 UTC, OlivierV79 approved these changes

2024-05-16 11:38 UTC, tcht-marie approved these changes

2024-05-16 12:20 UTC, ThibaultMesmin approved these changes

2024-05-16 13:00 UTC, morganb75 approved these changes

2024-05-17 06:26 UTC, merged